part of 'settings_cubit.dart'; // Generated by Cubit

@freezed
class SettingsState with _$SettingsState {
  const factory SettingsState({
    required ThemeMode themeMode,
    required Locale locale,
    required String currencyCode,
    @Default(false) bool isLoading, // To indicate if settings are being loaded/saved
    String? error, // To display any errors
  }) = _SettingsState;

  // Initial state factory
  factory SettingsState.initial() => SettingsState(
        themeMode: ThemeMode.system, // Default
        locale: const Locale('en', 'US'), // Default
        currencyCode: 'USD', // Default
      );
}