# l10n.yaml - Konfiguration f端r Flutter-Lokalisierung
arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/l10n/generated
# Unterst端tzte Sprachen
preferred-supported-locales:
  - en
  - de
# Keine Beschreibungen in separaten Dateien
use-deferred-loading: false
# Aktiviere Null-Safety
nullable-getter: false
# Synthetische Pakete f端r bessere Performance
synthetic-package: false
# Unterst端tzte Sprachen
untranslated-messages-file: lib/l10n/untranslated_messages.json