name: aboapp
description: "A Flutter app for subscription management, refactored for clarity and maintainability."
publish_to: 'none' # Prevent accidental publishing

version: 4.0.0+3 # Starting fresh version for the refactor
environment:
  sdk: '>=3.3.0 <4.0.0' # Targeting a recent Dart SDK

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # For internationalization
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6

  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.5.0

  # Immutable Data Classes & Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Routing
  go_router: ^14.2.0

  # UI & Utility
  intl: ^0.19.0
  uuid: ^4.4.0
  cached_network_image: ^3.3.1
  fl_chart: ^0.68.0
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.0
  cupertino_icons: ^1.0.8
  animations: ^2.0.11
  collection: ^1.18.0
  percent_indicator: ^4.2.3
  # NEUE ABHÄNGIGKEIT FÜR ANIMATIONEN
  flutter_staggered_animations: ^1.1.1
  enough_mail: ^2.1.6

  # Local Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.4
  flutter_secure_storage_web: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  injectable_generator: ^2.5.0
  go_router_builder: ^2.7.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/l10n/

flutter_native_splash:
  color: "#121212"
  image: assets/images/app_logo_splash.png
  android_12:
    color: "#121212"
    image: assets/images/app_logo_splash.png
  fullscreen: true
dependency_overrides:
  intl: 0.20.2
