part of 'subscription_cubit.dart'; // Generated by Cubit

@freezed
class SubscriptionState with _$SubscriptionState {
  const factory SubscriptionState.initial() = _Initial;
  const factory SubscriptionState.loading() = _Loading;
  const factory SubscriptionState.loaded({
    required List<SubscriptionEntity> allSubscriptions,
    required List<SubscriptionEntity> filteredSubscriptions, // For UI display after filtering/sorting
    // Add other relevant data for the UI, e.g., sorting options, filter values
    SortOption? currentSortOption,
    SubscriptionCategory? filterCategory,
    BillingCycle? filterBillingCycle,
    String? searchTerm,
  }) = _Loaded;
  const factory SubscriptionState.error({required String message}) = _Error;
}

// Enums for sorting and potentially filtering (can be moved to domain if they represent business logic)
enum SortOption { nameAsc, nameDesc, priceAsc, priceDesc, nextBillingDateAsc, nextBillingDateDesc, category }
// Filter enums (BillingCycle, SubscriptionCategory) are already defined in subscription_entity.dart